---
  - name: Download Apache Flume.
    get_url: url="{{ mirror_url }}/{{ version }}/apache-flume-{{ version }}-bin.tar.gz" dest="{{ download_path }}/apache-flume-{{ version }}-bin.tar.gz"
    environment: proxy_env

  - name: Uncompress Apache Flume.
    unarchive: src="{{ download_path }}/apache-flume-{{ version }}-bin.tar.gz" dest="{{ installation_path }}" copy=no

  - name: Make sure the directory has the right owner and group.
    file: path="{{ installation_path }}/apache-flume-{{ version }}-bin" owner=flume group=lambda

  - name: Create softlink for Apache Flume.
    file: src="{{ installation_path }}/apache-flume-{{ version }}-bin" dest="{{ installation_path }}/flume" state=link

  - name: Configure Apache Flume.
    template: src=flume-conf.properties.j2 dest="{{ installation_path }}/flume/conf/flume-conf.properties" owner=flume group=lambda mode=0644
    tags:
      - image-configure

  - name: Start Apache Flume.
    supervisorctl: name=apache_flume state=started
    tags:
      - image-configure
