---
  - name: Install apache2, apache2-dev and libapache2-mod-wsgi packages.
    apt: name={{ item }} state=latest
    with_items:
      - apache2
      - apache2-dev
      - libapache2-mod-wsgi

  - name: Install apache ssl module
    apache2_module: name={{item}} state=present
    with_items:
      - ssl
      - rewrite
    notify: restart_apache2

  - name: Create /etc/apache2/ssl directory
    file: path=/etc/apache2/ssl state=directory owner=root group=root mode=0744

  - name: Create self-signed certificate (to become deprecated)
    command: openssl req -new -nodes -x509 -subj "/C=GR/O=GRNET S.A./OU=okeanos.grnet.gr/CN={{ ansible_hostname }}" -days 3650 -keyout /etc/apache2/ssl/server.key -out /etc/apache2/ssl/server.crt -extensions v3_ca creates=/etc/apache2/ssl/server.crt

  - name: Change permissions of private key
    file: path=/etc/apache2/ssl/server.key mode=600 owner=root group=root

  - name: Change permissions of certificate
    file: path=/etc/apache2/ssl/server.crt mode=600 owner=root group=root

  - name: Copy Lambda sites-available configuration.
    template: src=central-service-backend.conf.j2 dest=/etc/apache2/sites-available/central-service-backend.conf

  - name: Copy lambda sites-available mkdocs configuration.
    template: src=central-service-mkdocs.conf.j2 dest=/etc/apache2/sites-available/central-service-mkdocs.conf

  - name: Copy lambda sites-available frontend configuration.
    template: src=central-service-frontend.conf.j2 dest=/etc/apache2/sites-available/central-service-frontend.conf

  - name: Add central-service-backend to sites-enabled.
    command: a2ensite central-service-backend.conf

  - name: Add central-service-mkdocs to sites-enabled.
    command: a2ensite central-service-mkdocs.conf

  - name: Add central-service-frontend to sites-enabled.
    command: a2ensite central-service-frontend.conf

  - name: Remove default sites-enabled.
    file: name=/etc/apache2/sites-enabled/000-default.conf state=absent

  - name: Activate Apache rewrite module.
    apache2_module: name=rewrite state=present
    notify:
          - restart_apache2

  - name: Activate Apache headers module.
    apache2_module: name=headers state=present
    notify:
          - restart_apache2

  - name: Configure Apache.
    lineinfile: dest=/etc/apache2/apache2.conf line="WSGIPythonPath {{ repository_download_path }}/okeanos-LoD/central_service/app" state=present insertafter=EOF
    notify:
      - restart_apache2
